[package]
name = "rust-taproot-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "0.32.0", features = ["rand-std"] }

[profile.release]
lto = true
strip = true
